name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Run automated tests (optional)
      - name: Run automated tests
        run: |
          node test.js  # Run the simple tests

      # Step 3: Build the web application
      - name: Build application
        run: |
          mkdir dist
          find . -mindepth 1 -maxdepth 1 ! -name dist -exec cp -r {} dist/ \;

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-web-app .

      # Step 5: Push the Docker image to Docker Hub (Optional)
      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag my-web-app $DOCKER_USERNAME/my-web-app:latest
          docker push $DOCKER_USERNAME/my-web-app:latest

      # Step 6: Show the contents of the build folder
      - name: Show build folder contents
        run: |
          ls dist
