name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (Optional, only if you need it)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Skip this if you don't use Node.js

      # Step 3: Install dependencies (Optional for a static site)
      - name: Install dependencies
        run: |
          echo "No dependencies to install for this project"

      # Step 4: Build the application
      - name: Build application
        run: |
          mkdir dist
          # Copy all files except the dist folder itself
          find . -mindepth 1 -maxdepth 1 ! -name dist -exec cp -r {} dist/ \;

      # Step 5: Show the build output (optional)
      - name: Show build folder contents
        run: |
          ls dist
