name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (skip install if you don't need it)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can remove this step if you don't need Node.js

      # Step 3: Skip the install step since no dependencies are needed
      # Run the simple tests without installing anything
      - name: Run automated tests
        run: |
          node test.js  # Run the simple tests

      # Step 4: Build the web application
      - name: Build application
        run: |
          mkdir dist
          find . -mindepth 1 -maxdepth 1 ! -name dist -exec cp -r {} dist/ \;

      # Step 5: Show the contents of the build folder
      - name: Show build folder contents
        run: |
          ls dist
