name: Deploy to Azure Web App with Docker

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your_dockerhub_username/azure-web-app .

      - name: Push Docker image to Docker Hub
        run: docker push your_dockerhub_username/azure-web-app:latest

      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-container-deploy@v2
        with:
          app-name: YOUR_APP_NAME  # Replace with your Azure Web App name
          images: your_dockerhub_username/azure-web-app:latest
