name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Build and push Docker image to Azure Container Registry (Optional)
      - name: Build Docker image and push to ACR (Optional if using Docker Hub)
        run: |
          docker build -t ghcr.io/${{ secrets.AZURE_WEBAPP_NAME }} .
          docker push ghcr.io/${{ secrets.AZURE_WEBAPP_NAME }}

      # Step 5: Deploy Docker container to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          images: ghcr.io/${{ secrets.AZURE_WEBAPP_NAME }}:latest
